#
AVATAR: "http://i.imgur.com/ydDFbp4.png?2"
AVATAR_DESC: "CollectQT Logo"
#
SITENAME: "CollectQT"
DESC: "A (Q)ueer (T)rans (Collect)ive"
URL: "http://collectqt.me"
#
GOOGLE_ANALYTICS: False
TWITTER_CARDS: False
TWITTER: "@collectqt"
FACEBOOK_OPENGRAPH: True
